<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.2.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderService.Services\OrderService.Services.csproj" />
    <ProjectReference Include="..\OrderService.Data\OrderService.Data.csproj" />
  </ItemGroup>

</Project>
